apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: sandbox-workload-security-binding
spec:
  policyName: sandbox-workload-security
  validationActions:
  - Deny
  matchResources:
    namespaceSelector:
      matchLabels:
        sandbox.dev/managed: "true"
